### ISSUE TITLE
Double pipe in rss path

### ISSUE THREAD

**Issue by llaraujo** [franklinjavier/franklinjavier#1]
Hi @franklinjavier :smile: !

Your config.json has a metadata.url with pipe in last char.

But in your header.hbt, has one pipe after variable:
```
{{url}}/rss.xml
``` 
Conclusion:
```
http://franklinjavier.com/blog//rss.xml
```

Bye bye! 

(Good Structure! :+1: )

**Comment by franklinjavier** [comment]
@llaraujo there is a lot of things to improve. This is an embryonic version.

Btw, thanks for pointing. 

:beer:

**Comment by franklinjavier** [comment]
@llaraujo working now \o

**Comment by llaraujo** [comment]
Yes! :beer:
